<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://sdk.axeda.com/webservices/registry/"
                  xmlns="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:apachesoap="http://xml.apache.org/xml-soap"
                  xmlns:impl="http://sdk.axeda.com/webservices/registry/"
                  xmlns:intf="http://sdk.axeda.com/webservices/registry/"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
                  xmlns:tns1="http://sdk.axeda.com/webservices/type"
                  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl1="http://sdk.axeda.com/webservices/model/"
                  xmlns:wsdl2="http://sdk.axeda.com/webservices/type/"
                  xmlns:wsdl3="http://sdk.axeda.com/webservices/type/">


  <wsdl:import namespace="http://sdk.axeda.com/webservices/type/" location="Types.wsdl"/>

  <wsdl:types>
    <schema targetNamespace="http://sdk.axeda.com/webservices/type" xmlns="http://www.w3.org/2001/XMLSchema">
      <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
    </schema>
  </wsdl:types>

  <wsdl:message name="Authentication">
    <wsdl:part name="Authentication" type="tns1:SessionInfo"/>
  </wsdl:message>

  <!-- start of fetching Named Packages -->
  <wsdl:message name="getRegistryDependencyEntriesRequest">
    <wsdl:part name="query" type="tns1:RegistryDependencyEntryQuery"/>
  </wsdl:message>

  <wsdl:message name="getRegistryDependencyEntriesResponse">
    <wsdl:part name="namedPackages" type="tns1:RegistryDependencyEntryList"/>
  </wsdl:message>
  <!-- ende of fetching Named Packages -->

  <wsdl:portType name="RegistryDependencyEntryService">
    <wsdl:operation name="getRegistryDependencyEntries" parameterOrder="query">
      <wsdl:input message="impl:getRegistryDependencyEntriesRequest" name="getRegistryDependencyEntriesRequest"/>
      <wsdl:output message="impl:getRegistryDependencyEntriesResponse" name="getRegistryDependencyEntriesResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="RegistryDependencyEntryServiceBinding" type="impl:RegistryDependencyEntryService">
    <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

    <wsdl:operation name="getRegistryDependencyEntries">
      <wsdlsoap:operation soapAction="GetRegistryDependencyEntries"/>
      <wsdl:input name="getRegistryDependencyEntriesRequest">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                       namespace="http://sdk.axeda.com/webservices/RegistryDependencyEntryService/" use="encoded"/>
        <wsdlsoap:header message="impl:Authentication" part="Authentication"
                         encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded"/>
      </wsdl:input>
      <wsdl:output name="getRegistryDependencyEntriesResponse">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                       namespace="http://sdk.axeda.com/webservices/RegistryDependencyEntryService/" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>

  </wsdl:binding>

  <wsdl:service name="RegistryDependencyEntryServiceService">
    <wsdl:port binding="impl:RegistryDependencyEntryServiceBinding" name="RegistryDependencyEntryService">
      <wsdlsoap:address location="http://sdk.axeda.com/webservices/services/RegistryDependencyEntryService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>